- name: variables
  hosts: localhost
  vars: #variable declaration
    trainer: "sudheer"
    course: "Ansible"
    duration: "30 days"
  tasks:
  - name: print overriding information
    vars:
      course: Terraform
    ansible.builtin.debug:
      msg: " This is a {{course}} course and trainer is {{trainer}} and duration is {{duration}}"

  - name: print global variable
    ansible.builtin.debug:
      msg: " This is a {{course}} course and trainer is {{trainer}} and duration is {{duration}}"