- name: check number
  hosts: localhost
  vars_prompt:
  - name: number
    prompt: please enter a number
    private: no

  tasks:
  - name: number is less than 10
    ansible.builtin.debug:
      msg: "given {{number}} is less than 10"
    when : number < 10