- name: loops
  hosts: localhost
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.dnf:
      name: "{{item}}"
      state: latest
    loop:
    - ansible
    - mysql
    - postfix
